/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duoyi_dyvoicesdk_api_DyVoiceAPI */

#ifndef _Included_com_duoyi_dyvoicesdk_api_DyVoiceAPI
#define _Included_com_duoyi_dyvoicesdk_api_DyVoiceAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duoyi_dyvoicesdk_api_DyVoiceAPI
 * Method:    setParameter
 * Signature: (IIIIZZI)I
 */
JNIEXPORT jint JNICALL Java_com_duoyi_dyvoicesdk_api_DyVoiceAPI_setParameter
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_duoyi_dyvoicesdk_api_DyVoiceAPI
 * Method:    startCall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_duoyi_dyvoicesdk_api_DyVoiceAPI_startCall
  (JNIEnv *, jobject);

/*
 * Class:     com_duoyi_dyvoicesdk_api_DyVoiceAPI
 * Method:    stopCall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_duoyi_dyvoicesdk_api_DyVoiceAPI_stopCall
  (JNIEnv *, jobject);

/*
 * Class:     com_duoyi_dyvoicesdk_api_DyVoiceAPI
 * Method:    encode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_duoyi_dyvoicesdk_api_DyVoiceAPI_encode
  (JNIEnv *, jobject);

/*
 * Class:     com_duoyi_dyvoicesdk_api_DyVoiceAPI
 * Method:    decode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_duoyi_dyvoicesdk_api_DyVoiceAPI_decode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
